:version: 0.0.1
:doctype: book

= Aggregate Javadoc Gradle Plugin

Provides support for producing an aggregate Javadoc that follows Gradle best practices.
This plugin is based on https://github.com/jjohannes/gradle-demos/blob/master/aggregated-javadoc[work by jjohannes].

== Usage

Releases are deployed to the Gradle Plugin Portal.
If you are using a SNAPSHOT, first ensure your `settings.gradle` is updated to resolve plugins from `repo.spring.io` as shown below:

.settings.gradle
[source,groovy]
----
pluginManagement {
	repositories {
		gradlePluginPortal()
		maven { url 'https://repo.spring.io/plugins-snapshots' }
	}
}
----

Next apply the plugin to each module that should be included in the aggregate Javadoc.
The `io.spring.javadoc` serves as a marker to determine which projects are included in the aggregate Javadoc.
As illustrated below, it is also necessary to apply the `JavaPlugin` to the project.

.build.gradle
[source,groovy,subs="+attributes"]
----
plugins {
	id 'java-library'
	id 'io.spring.javadoc' version '{version}'
}
----


Next apply the `AggregateJavadoc` plugin to a project that will produce the aggregate Javadoc.

.aggregator/build.gradle
[source,groovy,subs="+attributes"]
----
plugins {
	id 'io.spring.javadoc-aggregate' version '{version}'
}
----

This will create a task named `aggregateJavadoc` of type https://docs.gradle.org/current/dsl/org.gradle.api.tasks.javadoc.Javadoc.html[`Javadoc`].
The task defaults the https://docs.gradle.org/current/dsl/org.gradle.api.tasks.javadoc.Javadoc.html#org.gradle.api.tasks.javadoc.Javadoc:source[source] and https://docs.gradle.org/current/dsl/org.gradle.api.tasks.javadoc.Javadoc.html#org.gradle.api.tasks.javadoc.Javadoc:classpath[classpath] to aggregate values based on all of the projects that contain the `io.spring.javadoc` plugin.

Finally, run the task.

[source,bash]
----
./gradlew :aggregator:aggregateJavadoc
----


[NOTE]
====
For our example, we assume that `io.spring.javadoc-aggregate` is applied to the project `aggregator`.
You may apply to any module, but you will need to adjust the task accordingly.
====

You can customize which projects' Javadoc is aggregated by explicitly providing projects for the `implementation` configuration.
For example, the following explicitly aggregates `module1` and `module2` regardless of which projects have `io.spring.javadoc` applied to them.

[source,groovy]
----
plugins {
    id 'io.spring.javadoc-aggregate'
}

dependencies {
    implementation project(':module1')
    implementation project(':module3')
}
----

== License

This project is Open Source software released under the http://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license].
